[tool.poetry]
name = "python_training_session"
version = "0.0.1"
description = "Python Training Session Repo"
authors = ["Sudheer Kumar P.", "Haarthi Vijayaraghavan"]

[tool.poetry.dependencies]
python = ">=3.10, <4.0"
playwright = "^1.47.0"
pytest-playwright = "0.5.0"
